### ISSUE TITLE
Output files (e.g. label map) not found

### ISSUE THREAD

**Issue by emirkin** [google-research/lasertagger#12]
Error:
```tensorflow.python.framework.errors_impl.NotFoundError: output/label_map.txt.log; No such file or directory```

I followed the instructions to the letter: downloaded wiki-split and BERT (using the links from run_wikisplit_experiment.sh) and then set ```OUTPUT_DIR=output```.

Tail of the log:
```
I0609 12:19:06.618008 4580216256 phrase_vocabulary_optimization.py:190] 988000 examples processed.
I0609 12:19:07.309025 4580216256 phrase_vocabulary_optimization.py:190] 989000 examples processed.
I0609 12:19:07.954758 4580216256 phrase_vocabulary_optimization.py:202] 989944 examples processed.

Traceback (most recent call last):
  File "phrase_vocabulary_optimization.py", line 286, in <module>
    app.run(main)
  File "/Users/zheka/Library/Python/3.7/lib/python/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/zheka/Library/Python/3.7/lib/python/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "phrase_vocabulary_optimization.py", line 266, in main
    stats_writer.write('Idx\tFrequency\tCoverage (%)\tPhrase\n')
  File "/Users/zheka/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/lib/io/file_io.py", line 106, in write
    self._prewrite_check()
  File "/Users/zheka/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/lib/io/file_io.py", line 92, in _prewrite_check
    compat.as_bytes(self.__name), compat.as_bytes(self.__mode))
tensorflow.python.framework.errors_impl.NotFoundError: output/label_map.txt.log; No such file or directory
```

**Comment by emirkin** [comment]
Am I correct to assume that the missing files ought to be generated by the script and I don't need to install anything else beforehand?

**Comment by ekQ** [comment]
That's right, `label_map.txt.log` is a file that the script is supposed to generate. Please try:
1. Using a full path when setting `OUTPUT_DIR`.
2. Creating that directory in advance if it doesn't already exist.

**Comment by emirkin** [comment]
Creating the directory helped. Thank you.
